language: node_js
node_js:
- '0.10'
deploy:
  api_key:
    secure: Yj9Az8aJYgknaG0BCwmisAhYK+mKPT/P7XKDGT63MFJIh0TEwNuOu8nPc8zQt2AnkWdOyIhx8gF7JjmPlsNUMBbdoATZGm1C2L196YA0I89PZbIuzn7rCXbrq/6G5sTl7ejr3s2bUNFIEY0xAnvSIuImlWGuaXJO08o9CuRcXqw=